/**
 * Qur'an Constants & Metadata
 * Complete data for all 114 Surahs
 */

import { SurahMeta, PlanTemplate } from '../types';

/**
 * Complete metadata for all 114 Surahs of the Qur'an
 * Source: Verified from Islamic sources and Qur'an.com
 */
export const SURAHS: SurahMeta[] = [
  {
    number: 1,
    name: 'Al-Fatihah',
    nameArabic: 'الفاتحة',
    nameTransliteration: 'Al-Faatihah',
    revelationType: 'Meccan',
    numberOfAyahs: 7,
    numberOfPages: 1,
    juz: [1],
  },
  {
    number: 2,
    name: 'Al-Baqarah',
    nameArabic: 'البقرة',
    nameTransliteration: 'Al-Baqarah',
    revelationType: 'Medinan',
    numberOfAyahs: 286,
    numberOfPages: 48,
    juz: [1, 2, 3],
  },
  {
    number: 3,
    name: 'Aali Imran',
    nameArabic: 'آل عمران',
    nameTransliteration: 'Aal-i-Imraan',
    revelationType: 'Medinan',
    numberOfAyahs: 200,
    numberOfPages: 33,
    juz: [3, 4],
  },
  {
    number: 4,
    name: 'An-Nisa',
    nameArabic: 'النساء',
    nameTransliteration: 'An-Nisaa',
    revelationType: 'Medinan',
    numberOfAyahs: 176,
    numberOfPages: 29,
    juz: [4, 5, 6],
  },
  {
    number: 5,
    name: 'Al-Maidah',
    nameArabic: 'المائدة',
    nameTransliteration: 'Al-Maaida',
    revelationType: 'Medinan',
    numberOfAyahs: 120,
    numberOfPages: 21,
    juz: [6, 7],
  },
  {
    number: 6,
    name: 'Al-Anam',
    nameArabic: 'الأنعام',
    nameTransliteration: "Al-An'aam",
    revelationType: 'Meccan',
    numberOfAyahs: 165,
    numberOfPages: 24,
    juz: [7, 8],
  },
  {
    number: 7,
    name: 'Al-Araf',
    nameArabic: 'الأعراف',
    nameTransliteration: "Al-A'raaf",
    revelationType: 'Meccan',
    numberOfAyahs: 206,
    numberOfPages: 28,
    juz: [8, 9],
  },
  {
    number: 8,
    name: 'Al-Anfal',
    nameArabic: 'الأنفال',
    nameTransliteration: 'Al-Anfaal',
    revelationType: 'Medinan',
    numberOfAyahs: 75,
    numberOfPages: 11,
    juz: [9, 10],
  },
  {
    number: 9,
    name: 'At-Tawbah',
    nameArabic: 'التوبة',
    nameTransliteration: 'At-Tawbah',
    revelationType: 'Medinan',
    numberOfAyahs: 129,
    numberOfPages: 21,
    juz: [10, 11],
  },
  {
    number: 10,
    name: 'Yunus',
    nameArabic: 'يونس',
    nameTransliteration: 'Yunus',
    revelationType: 'Meccan',
    numberOfAyahs: 109,
    numberOfPages: 17,
    juz: [11],
  },
  {
    number: 11,
    name: 'Hud',
    nameArabic: 'هود',
    nameTransliteration: 'Hud',
    revelationType: 'Meccan',
    numberOfAyahs: 123,
    numberOfPages: 18,
    juz: [11, 12],
  },
  {
    number: 12,
    name: 'Yusuf',
    nameArabic: 'يوسف',
    nameTransliteration: 'Yusuf',
    revelationType: 'Meccan',
    numberOfAyahs: 111,
    numberOfPages: 17,
    juz: [12, 13],
  },
  {
    number: 13,
    name: 'Ar-Rad',
    nameArabic: 'الرعد',
    nameTransliteration: "Ar-Ra'd",
    revelationType: 'Medinan',
    numberOfAyahs: 43,
    numberOfPages: 8,
    juz: [13],
  },
  {
    number: 14,
    name: 'Ibrahim',
    nameArabic: 'ابراهيم',
    nameTransliteration: 'Ibrahim',
    revelationType: 'Meccan',
    numberOfAyahs: 52,
    numberOfPages: 8,
    juz: [13],
  },
  {
    number: 15,
    name: 'Al-Hijr',
    nameArabic: 'الحجر',
    nameTransliteration: 'Al-Hijr',
    revelationType: 'Meccan',
    numberOfAyahs: 99,
    numberOfPages: 7,
    juz: [14],
  },
  {
    number: 16,
    name: 'An-Nahl',
    nameArabic: 'النحل',
    nameTransliteration: 'An-Nahl',
    revelationType: 'Meccan',
    numberOfAyahs: 128,
    numberOfPages: 17,
    juz: [14],
  },
  {
    number: 17,
    name: 'Al-Isra',
    nameArabic: 'الإسراء',
    nameTransliteration: 'Al-Israa',
    revelationType: 'Meccan',
    numberOfAyahs: 111,
    numberOfPages: 15,
    juz: [15],
  },
  {
    number: 18,
    name: 'Al-Kahf',
    nameArabic: 'الكهف',
    nameTransliteration: 'Al-Kahf',
    revelationType: 'Meccan',
    numberOfAyahs: 110,
    numberOfPages: 17,
    juz: [15, 16],
  },
  {
    number: 19,
    name: 'Maryam',
    nameArabic: 'مريم',
    nameTransliteration: 'Maryam',
    revelationType: 'Meccan',
    numberOfAyahs: 98,
    numberOfPages: 12,
    juz: [16],
  },
  {
    number: 20,
    name: 'Ta-Ha',
    nameArabic: 'طه',
    nameTransliteration: 'Taa-Haa',
    revelationType: 'Meccan',
    numberOfAyahs: 135,
    numberOfPages: 17,
    juz: [16],
  },
  {
    number: 21,
    name: 'Al-Anbiya',
    nameArabic: 'الأنبياء',
    nameTransliteration: 'Al-Anbiyaa',
    revelationType: 'Meccan',
    numberOfAyahs: 112,
    numberOfPages: 15,
    juz: [17],
  },
  {
    number: 22,
    name: 'Al-Hajj',
    nameArabic: 'الحج',
    nameTransliteration: 'Al-Hajj',
    revelationType: 'Medinan',
    numberOfAyahs: 78,
    numberOfPages: 13,
    juz: [17],
  },
  {
    number: 23,
    name: 'Al-Muminun',
    nameArabic: 'المؤمنون',
    nameTransliteration: 'Al-Muminoon',
    revelationType: 'Meccan',
    numberOfAyahs: 118,
    numberOfPages: 12,
    juz: [18],
  },
  {
    number: 24,
    name: 'An-Nur',
    nameArabic: 'النور',
    nameTransliteration: 'An-Noor',
    revelationType: 'Medinan',
    numberOfAyahs: 64,
    numberOfPages: 12,
    juz: [18],
  },
  {
    number: 25,
    name: 'Al-Furqan',
    nameArabic: 'الفرقان',
    nameTransliteration: 'Al-Furqaan',
    revelationType: 'Meccan',
    numberOfAyahs: 77,
    numberOfPages: 10,
    juz: [18, 19],
  },
  {
    number: 26,
    name: 'Ash-Shuara',
    nameArabic: 'الشعراء',
    nameTransliteration: "Ash-Shu'araa",
    revelationType: 'Meccan',
    numberOfAyahs: 227,
    numberOfPages: 16,
    juz: [19],
  },
  {
    number: 27,
    name: 'An-Naml',
    nameArabic: 'النمل',
    nameTransliteration: 'An-Naml',
    revelationType: 'Meccan',
    numberOfAyahs: 93,
    numberOfPages: 11,
    juz: [19, 20],
  },
  {
    number: 28,
    name: 'Al-Qasas',
    nameArabic: 'القصص',
    nameTransliteration: 'Al-Qasas',
    revelationType: 'Meccan',
    numberOfAyahs: 88,
    numberOfPages: 13,
    juz: [20],
  },
  {
    number: 29,
    name: 'Al-Ankabut',
    nameArabic: 'العنكبوت',
    nameTransliteration: 'Al-Ankaboot',
    revelationType: 'Meccan',
    numberOfAyahs: 69,
    numberOfPages: 11,
    juz: [20, 21],
  },
  {
    number: 30,
    name: 'Ar-Rum',
    nameArabic: 'الروم',
    nameTransliteration: 'Ar-Room',
    revelationType: 'Meccan',
    numberOfAyahs: 60,
    numberOfPages: 9,
    juz: [21],
  },
  {
    number: 31,
    name: 'Luqman',
    nameArabic: 'لقمان',
    nameTransliteration: 'Luqman',
    revelationType: 'Meccan',
    numberOfAyahs: 34,
    numberOfPages: 5,
    juz: [21],
  },
  {
    number: 32,
    name: 'As-Sajdah',
    nameArabic: 'السجدة',
    nameTransliteration: 'As-Sajdah',
    revelationType: 'Meccan',
    numberOfAyahs: 30,
    numberOfPages: 5,
    juz: [21],
  },
  {
    number: 33,
    name: 'Al-Ahzab',
    nameArabic: 'الأحزاب',
    nameTransliteration: 'Al-Ahzaab',
    revelationType: 'Medinan',
    numberOfAyahs: 73,
    numberOfPages: 12,
    juz: [21, 22],
  },
  {
    number: 34,
    name: 'Saba',
    nameArabic: 'سبإ',
    nameTransliteration: 'Saba',
    revelationType: 'Meccan',
    numberOfAyahs: 54,
    numberOfPages: 9,
    juz: [22],
  },
  {
    number: 35,
    name: 'Fatir',
    nameArabic: 'فاطر',
    nameTransliteration: 'Faatir',
    revelationType: 'Meccan',
    numberOfAyahs: 45,
    numberOfPages: 7,
    juz: [22],
  },
  {
    number: 36,
    name: 'Ya-Sin',
    nameArabic: 'يس',
    nameTransliteration: 'Yaseen',
    revelationType: 'Meccan',
    numberOfAyahs: 83,
    numberOfPages: 9,
    juz: [22, 23],
  },
  {
    number: 37,
    name: 'As-Saffat',
    nameArabic: 'الصافات',
    nameTransliteration: 'As-Saaffaat',
    revelationType: 'Meccan',
    numberOfAyahs: 182,
    numberOfPages: 11,
    juz: [23],
  },
  {
    number: 38,
    name: 'Sad',
    nameArabic: 'ص',
    nameTransliteration: 'Saad',
    revelationType: 'Meccan',
    numberOfAyahs: 88,
    numberOfPages: 9,
    juz: [23],
  },
  {
    number: 39,
    name: 'Az-Zumar',
    nameArabic: 'الزمر',
    nameTransliteration: 'Az-Zumar',
    revelationType: 'Meccan',
    numberOfAyahs: 75,
    numberOfPages: 12,
    juz: [23, 24],
  },
  {
    number: 40,
    name: 'Ghafir',
    nameArabic: 'غافر',
    nameTransliteration: 'Ghaafir',
    revelationType: 'Meccan',
    numberOfAyahs: 85,
    numberOfPages: 13,
    juz: [24],
  },
  {
    number: 41,
    name: 'Fussilat',
    nameArabic: 'فصلت',
    nameTransliteration: 'Fussilat',
    revelationType: 'Meccan',
    numberOfAyahs: 54,
    numberOfPages: 9,
    juz: [24, 25],
  },
  {
    number: 42,
    name: 'Ash-Shuraa',
    nameArabic: 'الشورى',
    nameTransliteration: 'Ash-Shura',
    revelationType: 'Meccan',
    numberOfAyahs: 53,
    numberOfPages: 9,
    juz: [25],
  },
  {
    number: 43,
    name: 'Az-Zukhruf',
    nameArabic: 'الزخرف',
    nameTransliteration: 'Az-Zukhruf',
    revelationType: 'Meccan',
    numberOfAyahs: 89,
    numberOfPages: 11,
    juz: [25],
  },
  {
    number: 44,
    name: 'Ad-Dukhan',
    nameArabic: 'الدخان',
    nameTransliteration: 'Ad-Dukhaan',
    revelationType: 'Meccan',
    numberOfAyahs: 59,
    numberOfPages: 5,
    juz: [25],
  },
  {
    number: 45,
    name: 'Al-Jathiyah',
    nameArabic: 'الجاثية',
    nameTransliteration: 'Al-Jaathiya',
    revelationType: 'Meccan',
    numberOfAyahs: 37,
    numberOfPages: 5,
    juz: [25],
  },
  {
    number: 46,
    name: 'Al-Ahqaf',
    nameArabic: 'الأحقاف',
    nameTransliteration: 'Al-Ahqaf',
    revelationType: 'Meccan',
    numberOfAyahs: 35,
    numberOfPages: 6,
    juz: [26],
  },
  {
    number: 47,
    name: 'Muhammad',
    nameArabic: 'محمد',
    nameTransliteration: 'Muhammad',
    revelationType: 'Medinan',
    numberOfAyahs: 38,
    numberOfPages: 6,
    juz: [26],
  },
  {
    number: 48,
    name: 'Al-Fath',
    nameArabic: 'الفتح',
    nameTransliteration: 'Al-Fath',
    revelationType: 'Medinan',
    numberOfAyahs: 29,
    numberOfPages: 5,
    juz: [26],
  },
  {
    number: 49,
    name: 'Al-Hujurat',
    nameArabic: 'الحجرات',
    nameTransliteration: 'Al-Hujuraat',
    revelationType: 'Medinan',
    numberOfAyahs: 18,
    numberOfPages: 4,
    juz: [26],
  },
  {
    number: 50,
    name: 'Qaf',
    nameArabic: 'ق',
    nameTransliteration: 'Qaaf',
    revelationType: 'Meccan',
    numberOfAyahs: 45,
    numberOfPages: 5,
    juz: [26],
  },
  {
    number: 51,
    name: 'Adh-Dhariyat',
    nameArabic: 'الذاريات',
    nameTransliteration: 'Adh-Dhaariyat',
    revelationType: 'Meccan',
    numberOfAyahs: 60,
    numberOfPages: 5,
    juz: [26, 27],
  },
  {
    number: 52,
    name: 'At-Tur',
    nameArabic: 'الطور',
    nameTransliteration: 'At-Toor',
    revelationType: 'Meccan',
    numberOfAyahs: 49,
    numberOfPages: 4,
    juz: [27],
  },
  {
    number: 53,
    name: 'An-Najm',
    nameArabic: 'النجم',
    nameTransliteration: 'An-Najm',
    revelationType: 'Meccan',
    numberOfAyahs: 62,
    numberOfPages: 5,
    juz: [27],
  },
  {
    number: 54,
    name: 'Al-Qamar',
    nameArabic: 'القمر',
    nameTransliteration: 'Al-Qamar',
    revelationType: 'Meccan',
    numberOfAyahs: 55,
    numberOfPages: 5,
    juz: [27],
  },
  {
    number: 55,
    name: 'Ar-Rahman',
    nameArabic: 'الرحمن',
    nameTransliteration: 'Ar-Rahmaan',
    revelationType: 'Medinan',
    numberOfAyahs: 78,
    numberOfPages: 6,
    juz: [27],
  },
  {
    number: 56,
    name: 'Al-Waqiah',
    nameArabic: 'الواقعة',
    nameTransliteration: 'Al-Waaqia',
    revelationType: 'Meccan',
    numberOfAyahs: 96,
    numberOfPages: 7,
    juz: [27],
  },
  {
    number: 57,
    name: 'Al-Hadid',
    nameArabic: 'الحديد',
    nameTransliteration: 'Al-Hadeed',
    revelationType: 'Medinan',
    numberOfAyahs: 29,
    numberOfPages: 6,
    juz: [27],
  },
  {
    number: 58,
    name: 'Al-Mujadila',
    nameArabic: 'المجادلة',
    nameTransliteration: 'Al-Mujaadila',
    revelationType: 'Medinan',
    numberOfAyahs: 22,
    numberOfPages: 5,
    juz: [28],
  },
  {
    number: 59,
    name: 'Al-Hashr',
    nameArabic: 'الحشر',
    nameTransliteration: 'Al-Hashr',
    revelationType: 'Medinan',
    numberOfAyahs: 24,
    numberOfPages: 5,
    juz: [28],
  },
  {
    number: 60,
    name: 'Al-Mumtahanah',
    nameArabic: 'الممتحنة',
    nameTransliteration: 'Al-Mumtahana',
    revelationType: 'Medinan',
    numberOfAyahs: 13,
    numberOfPages: 4,
    juz: [28],
  },
  {
    number: 61,
    name: 'As-Saf',
    nameArabic: 'الصف',
    nameTransliteration: 'As-Saff',
    revelationType: 'Medinan',
    numberOfAyahs: 14,
    numberOfPages: 3,
    juz: [28],
  },
  {
    number: 62,
    name: 'Al-Jumuah',
    nameArabic: 'الجمعة',
    nameTransliteration: "Al-Jumu'a",
    revelationType: 'Medinan',
    numberOfAyahs: 11,
    numberOfPages: 2,
    juz: [28],
  },
  {
    number: 63,
    name: 'Al-Munafiqun',
    nameArabic: 'المنافقون',
    nameTransliteration: 'Al-Munaafiqoon',
    revelationType: 'Medinan',
    numberOfAyahs: 11,
    numberOfPages: 3,
    juz: [28],
  },
  {
    number: 64,
    name: 'At-Taghabun',
    nameArabic: 'التغابن',
    nameTransliteration: 'At-Taghaabun',
    revelationType: 'Medinan',
    numberOfAyahs: 18,
    numberOfPages: 3,
    juz: [28],
  },
  {
    number: 65,
    name: 'At-Talaq',
    nameArabic: 'الطلاق',
    nameTransliteration: 'At-Talaaq',
    revelationType: 'Medinan',
    numberOfAyahs: 12,
    numberOfPages: 3,
    juz: [28],
  },
  {
    number: 66,
    name: 'At-Tahrim',
    nameArabic: 'التحريم',
    nameTransliteration: 'At-Tahreem',
    revelationType: 'Medinan',
    numberOfAyahs: 12,
    numberOfPages: 3,
    juz: [28],
  },
  {
    number: 67,
    name: 'Al-Mulk',
    nameArabic: 'الملك',
    nameTransliteration: 'Al-Mulk',
    revelationType: 'Meccan',
    numberOfAyahs: 30,
    numberOfPages: 4,
    juz: [29],
  },
  {
    number: 68,
    name: 'Al-Qalam',
    nameArabic: 'القلم',
    nameTransliteration: 'Al-Qalam',
    revelationType: 'Meccan',
    numberOfAyahs: 52,
    numberOfPages: 4,
    juz: [29],
  },
  {
    number: 69,
    name: 'Al-Haqqah',
    nameArabic: 'الحاقة',
    nameTransliteration: 'Al-Haaqqa',
    revelationType: 'Meccan',
    numberOfAyahs: 52,
    numberOfPages: 4,
    juz: [29],
  },
  {
    number: 70,
    name: 'Al-Maarij',
    nameArabic: 'المعارج',
    nameTransliteration: "Al-Ma'aarij",
    revelationType: 'Meccan',
    numberOfAyahs: 44,
    numberOfPages: 3,
    juz: [29],
  },
  {
    number: 71,
    name: 'Nuh',
    nameArabic: 'نوح',
    nameTransliteration: 'Nooh',
    revelationType: 'Meccan',
    numberOfAyahs: 28,
    numberOfPages: 3,
    juz: [29],
  },
  {
    number: 72,
    name: 'Al-Jinn',
    nameArabic: 'الجن',
    nameTransliteration: 'Al-Jinn',
    revelationType: 'Meccan',
    numberOfAyahs: 28,
    numberOfPages: 3,
    juz: [29],
  },
  {
    number: 73,
    name: 'Al-Muzzammil',
    nameArabic: 'المزمل',
    nameTransliteration: 'Al-Muzzammil',
    revelationType: 'Meccan',
    numberOfAyahs: 20,
    numberOfPages: 3,
    juz: [29],
  },
  {
    number: 74,
    name: 'Al-Muddaththir',
    nameArabic: 'المدثر',
    nameTransliteration: 'Al-Muddaththir',
    revelationType: 'Meccan',
    numberOfAyahs: 56,
    numberOfPages: 4,
    juz: [29],
  },
  {
    number: 75,
    name: 'Al-Qiyamah',
    nameArabic: 'القيامة',
    nameTransliteration: 'Al-Qiyaamah',
    revelationType: 'Meccan',
    numberOfAyahs: 40,
    numberOfPages: 3,
    juz: [29],
  },
  {
    number: 76,
    name: 'Al-Insan',
    nameArabic: 'الانسان',
    nameTransliteration: 'Al-Insaan',
    revelationType: 'Medinan',
    numberOfAyahs: 31,
    numberOfPages: 3,
    juz: [29],
  },
  {
    number: 77,
    name: 'Al-Mursalat',
    nameArabic: 'المرسلات',
    nameTransliteration: 'Al-Mursalaat',
    revelationType: 'Meccan',
    numberOfAyahs: 50,
    numberOfPages: 3,
    juz: [29],
  },
  {
    number: 78,
    name: 'An-Naba',
    nameArabic: 'النبإ',
    nameTransliteration: 'An-Naba',
    revelationType: 'Meccan',
    numberOfAyahs: 40,
    numberOfPages: 3,
    juz: [30],
  },
  {
    number: 79,
    name: 'An-Naziat',
    nameArabic: 'النازعات',
    nameTransliteration: "An-Naazi'aat",
    revelationType: 'Meccan',
    numberOfAyahs: 46,
    numberOfPages: 3,
    juz: [30],
  },
  {
    number: 80,
    name: 'Abasa',
    nameArabic: 'عبس',
    nameTransliteration: 'Abasa',
    revelationType: 'Meccan',
    numberOfAyahs: 42,
    numberOfPages: 2,
    juz: [30],
  },
  {
    number: 81,
    name: 'At-Takwir',
    nameArabic: 'التكوير',
    nameTransliteration: 'At-Takweer',
    revelationType: 'Meccan',
    numberOfAyahs: 29,
    numberOfPages: 2,
    juz: [30],
  },
  {
    number: 82,
    name: 'Al-Infitar',
    nameArabic: 'الإنفطار',
    nameTransliteration: 'Al-Infitaar',
    revelationType: 'Meccan',
    numberOfAyahs: 19,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 83,
    name: 'Al-Mutaffifin',
    nameArabic: 'المطففين',
    nameTransliteration: 'Al-Mutaffifin',
    revelationType: 'Meccan',
    numberOfAyahs: 36,
    numberOfPages: 2,
    juz: [30],
  },
  {
    number: 84,
    name: 'Al-Inshiqaq',
    nameArabic: 'الإنشقاق',
    nameTransliteration: 'Al-Inshiqaaq',
    revelationType: 'Meccan',
    numberOfAyahs: 25,
    numberOfPages: 2,
    juz: [30],
  },
  {
    number: 85,
    name: 'Al-Buruj',
    nameArabic: 'البروج',
    nameTransliteration: 'Al-Burooj',
    revelationType: 'Meccan',
    numberOfAyahs: 22,
    numberOfPages: 2,
    juz: [30],
  },
  {
    number: 86,
    name: 'At-Tariq',
    nameArabic: 'الطارق',
    nameTransliteration: 'At-Taariq',
    revelationType: 'Meccan',
    numberOfAyahs: 17,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 87,
    name: 'Al-Ala',
    nameArabic: 'الأعلى',
    nameTransliteration: "Al-A'laa",
    revelationType: 'Meccan',
    numberOfAyahs: 19,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 88,
    name: 'Al-Ghashiyah',
    nameArabic: 'الغاشية',
    nameTransliteration: 'Al-Ghaashiya',
    revelationType: 'Meccan',
    numberOfAyahs: 26,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 89,
    name: 'Al-Fajr',
    nameArabic: 'الفجر',
    nameTransliteration: 'Al-Fajr',
    revelationType: 'Meccan',
    numberOfAyahs: 30,
    numberOfPages: 2,
    juz: [30],
  },
  {
    number: 90,
    name: 'Al-Balad',
    nameArabic: 'البلد',
    nameTransliteration: 'Al-Balad',
    revelationType: 'Meccan',
    numberOfAyahs: 20,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 91,
    name: 'Ash-Shams',
    nameArabic: 'الشمس',
    nameTransliteration: 'Ash-Shams',
    revelationType: 'Meccan',
    numberOfAyahs: 15,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 92,
    name: 'Al-Layl',
    nameArabic: 'الليل',
    nameTransliteration: 'Al-Lail',
    revelationType: 'Meccan',
    numberOfAyahs: 21,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 93,
    name: 'Ad-Duhaa',
    nameArabic: 'الضحى',
    nameTransliteration: 'Ad-Dhuhaa',
    revelationType: 'Meccan',
    numberOfAyahs: 11,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 94,
    name: 'Ash-Sharh',
    nameArabic: 'الشرح',
    nameTransliteration: 'Ash-Sharh',
    revelationType: 'Meccan',
    numberOfAyahs: 8,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 95,
    name: 'At-Tin',
    nameArabic: 'التين',
    nameTransliteration: 'At-Teen',
    revelationType: 'Meccan',
    numberOfAyahs: 8,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 96,
    name: 'Al-Alaq',
    nameArabic: 'العلق',
    nameTransliteration: 'Al-Alaq',
    revelationType: 'Meccan',
    numberOfAyahs: 19,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 97,
    name: 'Al-Qadr',
    nameArabic: 'القدر',
    nameTransliteration: 'Al-Qadr',
    revelationType: 'Meccan',
    numberOfAyahs: 5,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 98,
    name: 'Al-Bayyinah',
    nameArabic: 'البينة',
    nameTransliteration: 'Al-Bayyina',
    revelationType: 'Medinan',
    numberOfAyahs: 8,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 99,
    name: 'Az-Zalzalah',
    nameArabic: 'الزلزلة',
    nameTransliteration: 'Az-Zalzala',
    revelationType: 'Medinan',
    numberOfAyahs: 8,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 100,
    name: 'Al-Adiyat',
    nameArabic: 'العاديات',
    nameTransliteration: 'Al-Aadiyaat',
    revelationType: 'Meccan',
    numberOfAyahs: 11,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 101,
    name: 'Al-Qariah',
    nameArabic: 'القارعة',
    nameTransliteration: "Al-Qaari'a",
    revelationType: 'Meccan',
    numberOfAyahs: 11,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 102,
    name: 'At-Takathur',
    nameArabic: 'التكاثر',
    nameTransliteration: 'At-Takaathur',
    revelationType: 'Meccan',
    numberOfAyahs: 8,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 103,
    name: 'Al-Asr',
    nameArabic: 'العصر',
    nameTransliteration: 'Al-Asr',
    revelationType: 'Meccan',
    numberOfAyahs: 3,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 104,
    name: 'Al-Humazah',
    nameArabic: 'الهمزة',
    nameTransliteration: 'Al-Humaza',
    revelationType: 'Meccan',
    numberOfAyahs: 9,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 105,
    name: 'Al-Fil',
    nameArabic: 'الفيل',
    nameTransliteration: 'Al-Feel',
    revelationType: 'Meccan',
    numberOfAyahs: 5,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 106,
    name: 'Quraysh',
    nameArabic: 'قريش',
    nameTransliteration: 'Quraish',
    revelationType: 'Meccan',
    numberOfAyahs: 4,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 107,
    name: 'Al-Maun',
    nameArabic: 'الماعون',
    nameTransliteration: "Al-Maa'oon",
    revelationType: 'Meccan',
    numberOfAyahs: 7,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 108,
    name: 'Al-Kawthar',
    nameArabic: 'الكوثر',
    nameTransliteration: 'Al-Kawthar',
    revelationType: 'Meccan',
    numberOfAyahs: 3,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 109,
    name: 'Al-Kafirun',
    nameArabic: 'الكافرون',
    nameTransliteration: 'Al-Kaafiroon',
    revelationType: 'Meccan',
    numberOfAyahs: 6,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 110,
    name: 'An-Nasr',
    nameArabic: 'النصر',
    nameTransliteration: 'An-Nasr',
    revelationType: 'Medinan',
    numberOfAyahs: 3,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 111,
    name: 'Al-Masad',
    nameArabic: 'المسد',
    nameTransliteration: 'Al-Masad',
    revelationType: 'Meccan',
    numberOfAyahs: 5,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 112,
    name: 'Al-Ikhlas',
    nameArabic: 'الإخلاص',
    nameTransliteration: 'Al-Ikhlaas',
    revelationType: 'Meccan',
    numberOfAyahs: 4,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 113,
    name: 'Al-Falaq',
    nameArabic: 'الفلق',
    nameTransliteration: 'Al-Falaq',
    revelationType: 'Meccan',
    numberOfAyahs: 5,
    numberOfPages: 1,
    juz: [30],
  },
  {
    number: 114,
    name: 'An-Nas',
    nameArabic: 'الناس',
    nameTransliteration: 'An-Naas',
    revelationType: 'Meccan',
    numberOfAyahs: 6,
    numberOfPages: 1,
    juz: [30],
  },
];

/**
 * Get Surah by number
 */
export const getSurahByNumber = (number: number): SurahMeta | undefined => {
  return SURAHS.find(surah => surah.number === number);
};

/**
 * Get Surahs by Juz number
 */
export const getSurahsByJuz = (juz: number): SurahMeta[] => {
  return SURAHS.filter(surah => surah.juz.includes(juz));
};

/**
 * Get Meccan Surahs
 */
export const getMeccanSurahs = (): SurahMeta[] => {
  return SURAHS.filter(surah => surah.revelationType === 'Meccan');
};

/**
 * Get Medinan Surahs
 */
export const getMedinanSurahs = (): SurahMeta[] => {
  return SURAHS.filter(surah => surah.revelationType === 'Medinan');
};

/**
 * Total pages in the Quran (standard Mushaf)
 */
export const TOTAL_QURAN_PAGES = 604;

/**
 * Total verses in the Quran
 */
export const TOTAL_QURAN_VERSES = 6236;

/**
 * Total Juz (parts) in the Quran
 */
export const TOTAL_JUZ = 30;

/**
 * Pre-defined Reading Plan Templates
 */
export const PLAN_TEMPLATES: PlanTemplate[] = [
  {
    id: 'quick-7day',
    name: '7-Day Mini Plan',
    description: 'Read Surah Yaseen and other short surahs over 7 days',
    mode: 'pages',
    targetPerDay: 3,
    totalTarget: 21,
    durationDays: 7,
    icon: 'calendar',
  },
  {
    id: 'standard-30day',
    name: 'Complete Quran in 30 Days',
    description: 'Finish the entire Quran in one month - 1 Juz per day',
    mode: 'pages',
    targetPerDay: 20,
    totalTarget: 604,
    durationDays: 30,
    icon: 'book',
  },
  {
    id: 'ramadan-plan',
    name: 'Ramadan Reading Plan',
    description: 'Complete the Quran during Ramadan - 1 Juz per day',
    mode: 'pages',
    targetPerDay: 20,
    totalTarget: 604,
    durationDays: 30,
    icon: 'moon',
  },
  {
    id: 'moderate-60day',
    name: 'Quran in 60 Days',
    description: 'Complete the Quran in 2 months - steady pace',
    mode: 'pages',
    targetPerDay: 10,
    totalTarget: 604,
    durationDays: 60,
    icon: 'book-open',
  },
  {
    id: 'gradual-90day',
    name: 'Quran in 90 Days',
    description: 'Complete the Quran in 3 months - gentle pace',
    mode: 'pages',
    targetPerDay: 7,
    totalTarget: 604,
    durationDays: 90,
    icon: 'bookmark',
  },
  {
    id: 'daily-verses',
    name: 'Daily 10 Verses',
    description: 'Read 10 verses every day - ongoing practice',
    mode: 'verses',
    targetPerDay: 10,
    durationDays: 365,
    icon: 'list',
  },
  {
    id: 'daily-time',
    name: 'Daily 15 Minutes',
    description: 'Spend 15 minutes reading each day',
    mode: 'time',
    targetPerDay: 15,
    durationDays: 365,
    icon: 'clock',
  },
];

/**
 * Reflection Prompts for Tadabbur
 */
export const REFLECTION_PROMPTS = [
  'Which ayah touched your heart today?',
  'How does this verse help you handle difficulty?',
  'What action will you take to strengthen trust in Allah?',
  "Which ayah reminded you of Allah's blessings today?",
  'What new understanding did you gain from this reading?',
  'How can you apply this lesson to your daily life?',
  'What does this verse teach about your relationship with Allah?',
  'Which verse gave you hope or comfort?',
  'What reminder did you receive about patience?',
  'How does this passage inspire you to be better?',
];

/**
 * Authentic Hadith about Quran Reading
 */
export const QURAN_HADITHS = [
  {
    text: "Recite the Qur'an, for it will come as an intercessor for its companions on the Day of Resurrection.",
    reference: 'Sahih Muslim 804',
    theme: 'virtue',
  },
  {
    text: "The best of you are those who learn the Qur'an and teach it.",
    reference: 'Sahih al-Bukhari 5027',
    theme: 'learning',
  },
  {
    text: 'Whoever reads a letter from the Book of Allah will receive a hasanah (good deed), and the hasanah is multiplied by ten.',
    reference: "Jami' at-Tirmidhi 2910",
    theme: 'reward',
  },
  {
    text: "Do they not then reflect on the Qur'an? Or are there locks upon their hearts?",
    reference: 'Quran 47:24',
    theme: 'reflection',
  },
  {
    text: "Verily, the one who has nothing of the Qur'an in his heart is like a ruined house.",
    reference: "Jami' at-Tirmidhi 2913",
    theme: 'memorization',
  },
];

/**
 * Available Translations
 */
export const AVAILABLE_TRANSLATIONS = [
  { id: 'en.sahih', name: 'Sahih International', language: 'English' },
  { id: 'en.pickthall', name: 'Pickthall', language: 'English' },
  { id: 'en.yusufali', name: 'Yusuf Ali', language: 'English' },
  { id: 'ar.muyassar', name: 'Tafsir Al-Muyassar', language: 'Arabic' },
];

/**
 * Default Reciter
 */
export const DEFAULT_RECITER = 'ar.alafasy';

/**
 * Available Reciters for Audio
 * Sorted by popularity and quality
 * NOTE: Only includes reciters verified to work with cdn.islamic.network/quran/audio/128/
 * All reciters tested and confirmed working as of 2025
 */
export const AVAILABLE_RECITERS = [
  // Most Popular - Verified Working Reciters
  {
    id: 'ar.alafasy',
    name: 'Mishary Rashid Alafasy',
    locale: 'Arabic',
    country: 'Kuwait',
    style: 'Clear, melodious recitation - Very popular worldwide',
    verified: true,
  },
  {
    id: 'ar.husary',
    name: 'Mahmoud Khalil Al-Husary',
    locale: 'Arabic',
    country: 'Egypt',
    style: 'Educational murattal - Excellent for tajweed learning',
    verified: true,
  },
  {
    id: 'ar.husarymujawwad',
    name: 'Mahmoud Khalil Al-Husary (Mujawwad)',
    locale: 'Arabic',
    country: 'Egypt',
    style: 'Melodious mujawwad style - Beautiful and precise',
    verified: true,
  },
  {
    id: 'ar.minshawi',
    name: 'Mohamed Siddiq Al-Minshawi',
    locale: 'Arabic',
    country: 'Egypt',
    style: 'Classic, masterful mujawwad recitation',
    verified: true,
  },
  {
    id: 'ar.mahermuaiqly',
    name: 'Maher Al Muaiqly',
    locale: 'Arabic',
    country: 'Saudi Arabia',
    style: 'Imam of Masjid al-Haram - Beautiful, moving recitation',
    verified: true,
  },
  {
    id: 'ar.shaatree',
    name: 'Abu Bakr Ash-Shaatree',
    locale: 'Arabic',
    country: 'Saudi Arabia',
    style: 'Imam of Masjid al-Haram - Clear and powerful',
    verified: true,
  },
  {
    id: 'ar.muhammadayyoub',
    name: 'Muhammad Ayyoub',
    locale: 'Arabic',
    country: 'Saudi Arabia',
    style: 'Former Imam of Masjid al-Nabawi - Deep, resonant voice',
    verified: true,
  },
  {
    id: 'ar.hudhaify',
    name: 'Ali bin Abdur-Rahman Al-Huthaify',
    locale: 'Arabic',
    country: 'Saudi Arabia',
    style: 'Former Imam of Masjid al-Nabawi - Powerful recitation',
    verified: true,
  },
  {
    id: 'ar.ahmedajamy',
    name: 'Ahmad Al-Ajamy',
    locale: 'Arabic',
    country: 'Saudi Arabia',
    style: 'Beautiful mujawwad recitation - Very melodious',
    verified: true,
  },
  {
    id: 'ar.muhammadjibreel',
    name: 'Muhammad Jibreel',
    locale: 'Arabic',
    country: 'Egypt',
    style: 'Powerful, moving voice - Highly respected',
    verified: true,
  },
  // Note: The fallback system ensures ar.alafasy plays if a reciter becomes unavailable
];
